from __future__ import print_function
import requests, json

## default port for bitcoin testnet
## (change to 8332 for 'main net'),
rpcPort = 18332
rpcUser = 'bitcoinrpc'
## not a real password
## but if you use the random password generated by bitcoind
## your password should look something like this
rpcPassword = 'rpc'
serverURL = 'http://' + rpcUser + ':' + rpcPassword + '@localhost:' + str(rpcPort)

headers = {'content-type': 'application/json'}
payload = {
	"method": 'signrawtransaction',
	"params": ["0100000001b66854c9c8dc49c35416eede7d25c0eafe74ef20f69037daed8e6576cc47ca81000000001976a91411046b18f21dfd48c288bf46e45d4d1a479b78c988acffffffff0336150000000000001976a91462a3a6d420755fd51e5ae857981aa218abc7fe9888ac00000000000000001e6a1caf3832e4d0a75a8801b132b86833b9f8f36116dc5b93627c4fab83340f3d1b0c000000001976a91411046b18f21dfd48c288bf46e45d4d1a479b78c988ac00000000"],
	"jsonrpc": "2.0"
	}
response = requests.post(serverURL, headers=headers, data=json.dumps(payload))
print(response.text)